### ISSUE TITLE
feat: alert user to failed login with message

### ISSUE THREAD

**Issue by Danondso** [Danondso/bedfellow#39]
right now if login fails we just stay on the screen without any indication, let's add a snackbar or modal to indicate what happened

**Comment by Subham5401** [comment]
Hey @Danondso, I'd like to take this.

**Comment by Danondso** [comment]
Hey @Subham5401, all yours I'll assign it to you. Let me know if you have trouble setting up

**Comment by Subham5401** [comment]
Hello, @Danondso. I'm currently experiencing some difficulties while setting up the project. Could you please unassign the issue for now? I remain eager to contribute in the future.

**Comment by Danondso** [comment]
Yeah that's cool. If you don't mind mentioning what the difficulties are that would help me to make setting this up easier

**Comment by Danondso** [comment]
@Subham5401 I've updated the project with clearer setup steps and moved away from using the old spotify auth library so Android should work now. If you wanted to try giving it a go again let me know.

**Comment by Danondso** [comment]
Closed by #63
